// Auto-generated from services\btdrv.h
// DO NOT EDIT MANUALLY

#pragma warning disable CS0649, CS0169, CS8981

namespace LibNX.Services;

public unsafe struct BtdrvCircularBuffer
{
    public Mutex mutex;
    public IntPtr event_type;
    public u8 data;
    public s32 write_offset;
    public s32 read_offset;
    public u64 utilization;
    public byte name;
    public u8 initialized;
}

public static class Btdrv
{
    public static extern Result btdrvInitialize();
    public static extern void btdrvExit();
    public static extern IntPtr btdrvGetServiceSession();
    public static extern Result btdrvInitializeBluetooth(ref Event out_event);
    public static extern Result btdrvEnableBluetooth();
    public static extern Result btdrvDisableBluetooth();
    public static extern Result btdrvFinalizeBluetooth();
    public static extern Result btdrvLegacyGetAdapterProperties(ref BtdrvAdapterPropertyOld properties);
    public static extern Result btdrvGetAdapterProperties(ref BtdrvAdapterPropertySet properties);
    public static extern Result btdrvLegacyGetAdapterProperty(BtdrvBluetoothPropertyType type, IntPtr buffer, ulong size);
    public static extern Result btdrvGetAdapterProperty(BtdrvAdapterPropertyType type, ref BtdrvAdapterProperty property);
    public static extern Result btdrvLegacySetAdapterProperty(BtdrvBluetoothPropertyType type, IntPtr buffer, ulong size);
    public static extern Result btdrvSetAdapterProperty(BtdrvAdapterPropertyType type, ref BtdrvAdapterProperty property);
    public static extern Result btdrvLegacyStartInquiry();
    public static extern Result btdrvStartInquiry(u32 services, s64 duration);
    public static extern Result btdrvStopInquiry();
    public static extern Result btdrvCreateBond(BtdrvAddress addr, u32 type);
    public static extern Result btdrvRemoveBond(BtdrvAddress addr);
    public static extern Result btdrvCancelBond(BtdrvAddress addr);
    public static extern Result btdrvLegacyRespondToPinRequest(BtdrvAddress addr, bool flag, ref BtdrvBluetoothPinCode pin_code, u8 length);
    public static extern Result btdrvRespondToPinRequest(BtdrvAddress addr, ref BtdrvPinCode pin_code);
    public static extern Result btdrvRespondToSspRequest(BtdrvAddress addr, u32 variant, bool accept, u32 passkey);
    public static extern Result btdrvGetEventInfo(IntPtr buffer, ulong size, ref BtdrvEventType type);
    public static extern Result btdrvInitializeHid(ref Event out_event);
    public static extern Result btdrvOpenHidConnection(BtdrvAddress addr);
    public static extern Result btdrvCloseHidConnection(BtdrvAddress addr);
    public static extern Result btdrvWriteHidData(BtdrvAddress addr, ref BtdrvHidReport buffer);
    public static extern Result btdrvWriteHidData2(BtdrvAddress addr, IntPtr buffer, ulong size);
    public static extern Result btdrvSetHidReport(BtdrvAddress addr, BtdrvBluetoothHhReportType type, ref BtdrvHidReport buffer);
    public static extern Result btdrvGetHidReport(BtdrvAddress addr, u8 report_id, BtdrvBluetoothHhReportType type);
    public static extern Result btdrvTriggerConnection(BtdrvAddress addr, u16 timeout);
    public static extern Result btdrvAddPairedDeviceInfo(ref SetSysBluetoothDevicesSettings settings);
    public static extern Result btdrvGetPairedDeviceInfo(BtdrvAddress addr, ref SetSysBluetoothDevicesSettings settings);
    public static extern Result btdrvFinalizeHid();
    public static extern Result btdrvGetHidEventInfo(IntPtr buffer, ulong size, ref BtdrvHidEventType type);
    public static extern Result btdrvSetTsi(BtdrvAddress addr, u8 tsi);
    public static extern Result btdrvEnableBurstMode(BtdrvAddress addr, bool flag);
    public static extern Result btdrvSetZeroRetransmission(BtdrvAddress addr, ref u8 report_ids, u8 count);
    public static extern Result btdrvEnableMcMode(bool flag);
    public static extern Result btdrvEnableLlrScan();
    public static extern Result btdrvDisableLlrScan();
    public static extern Result btdrvEnableRadio(bool flag);
    public static extern Result btdrvSetVisibility(bool inquiry_scan, bool page_scan);
    public static extern Result btdrvEnableTbfcScan(bool flag);
    public static extern Result btdrvRegisterHidReportEvent(ref Event out_event);
    public static extern Result btdrvGetHidReportEventInfo(IntPtr buffer, ulong size, ref BtdrvHidEventType type);
    public static extern IntPtr btdrvGetHidReportEventInfoSharedmemAddr();
    public static extern Result btdrvGetLatestPlr(ref BtdrvPlrList @out);
    public static extern Result btdrvGetPendingConnections();
    public static extern Result btdrvGetChannelMap(ref BtdrvChannelMapList @out);
    public static extern Result btdrvEnableTxPowerBoostSetting(bool flag);
    public static extern Result btdrvIsTxPowerBoostSettingEnabled(ref bool @out);
    public static extern Result btdrvEnableAfhSetting(bool flag);
    public static extern Result btdrvIsAfhSettingEnabled(ref bool @out);
    public static extern Result btdrvInitializeBle(ref Event out_event);
    public static extern Result btdrvEnableBle();
    public static extern Result btdrvDisableBle();
    public static extern Result btdrvFinalizeBle();
    public static extern Result btdrvSetBleVisibility(bool discoverable, bool connectable);
    public static extern Result btdrvSetLeConnectionParameter(ref BtdrvLeConnectionParams param);
    public static extern Result btdrvSetBleConnectionParameter(BtdrvAddress addr, ref BtdrvBleConnectionParameter param, bool preference);
    public static extern Result btdrvSetLeDefaultConnectionParameter(ref BtdrvLeConnectionParams param);
    public static extern Result btdrvSetBleDefaultConnectionParameter(ref BtdrvBleConnectionParameter param);
    public static extern Result btdrvSetBleAdvertiseData(ref BtdrvBleAdvertisePacketData data);
    public static extern Result btdrvSetBleAdvertiseParameter(BtdrvAddress addr, u16 min_interval, u16 max_interval);
    public static extern Result btdrvStartBleScan();
    public static extern Result btdrvStopBleScan();
    public static extern Result btdrvAddBleScanFilterCondition(ref BtdrvBleAdvertiseFilter filter);
    public static extern Result btdrvDeleteBleScanFilterCondition(ref BtdrvBleAdvertiseFilter filter);
    public static extern Result btdrvDeleteBleScanFilter(u8 index);
    public static extern Result btdrvClearBleScanFilters();
    public static extern Result btdrvEnableBleScanFilter(bool flag);
    public static extern Result btdrvRegisterGattClient(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvUnregisterGattClient(u8 client_if);
    public static extern Result btdrvUnregisterAllGattClients();
    public static extern Result btdrvConnectGattServer(u8 client_if, BtdrvAddress addr, bool is_direct, u64 AppletResourceUserId);
    public static extern Result btdrvCancelConnectGattServer(u8 client_if, BtdrvAddress addr, bool is_direct);
    public static extern Result btdrvDisconnectGattServer(u32 conn_id);
    public static extern Result btdrvGetGattAttribute(BtdrvAddress addr, u32 conn_id);
    public static extern Result btdrvGetGattService(u32 conn_id, ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvConfigureAttMtu(u32 conn_id, u16 mtu);
    public static extern Result btdrvRegisterGattServer(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvUnregisterGattServer(u8 server_if);
    public static extern Result btdrvConnectGattClient(u8 server_if, BtdrvAddress addr, bool is_direct);
    public static extern Result btdrvDisconnectGattClient(u8 conn_id, BtdrvAddress addr);
    public static extern Result btdrvAddGattService(u8 server_if, ref BtdrvGattAttributeUuid uuid, u8 num_handle, bool is_primary);
    public static extern Result btdrvEnableGattService(u8 server_if, ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvAddGattCharacteristic(u8 server_if, ref BtdrvGattAttributeUuid serv_uuid, ref BtdrvGattAttributeUuid char_uuid, u16 permissions, u8 property);
    public static extern Result btdrvAddGattDescriptor(u8 server_if, ref BtdrvGattAttributeUuid serv_uuid, ref BtdrvGattAttributeUuid desc_uuid, u16 permissions);
    public static extern Result btdrvGetBleManagedEventInfo(IntPtr buffer, ulong size, ref BtdrvBleEventType type);
    public static extern Result btdrvGetGattFirstCharacteristic(u32 conn_id, ref BtdrvGattId serv_id, bool is_primary, ref BtdrvGattAttributeUuid filter_uuid, ref u8 out_property, ref BtdrvGattId out_char_id);
    public static extern Result btdrvGetGattNextCharacteristic(u32 conn_id, ref BtdrvGattId serv_id, bool is_primary, ref BtdrvGattId char_id, ref BtdrvGattAttributeUuid filter_uuid, ref u8 out_property, ref BtdrvGattId out_char_id);
    public static extern Result btdrvGetGattFirstDescriptor(u32 conn_id, ref BtdrvGattId serv_id, bool is_primary, ref BtdrvGattId char_id, ref BtdrvGattAttributeUuid filter_uuid, ref BtdrvGattId out_desc_id);
    public static extern Result btdrvGetGattNextDescriptor(u32 conn_id, ref BtdrvGattId serv_id, bool is_primary, ref BtdrvGattId char_id, ref BtdrvGattId desc_id, ref BtdrvGattAttributeUuid filter_uuid, ref BtdrvGattId out_desc_id);
    public static extern Result btdrvRegisterGattManagedDataPath(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvUnregisterGattManagedDataPath(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvRegisterGattHidDataPath(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvUnregisterGattHidDataPath(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvRegisterGattDataPath(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvUnregisterGattDataPath(ref BtdrvGattAttributeUuid uuid);
    public static extern Result btdrvReadGattCharacteristic(u32 connection_handle, bool is_primary, ref BtdrvGattId serv_id, ref BtdrvGattId char_id, u8 auth_req);
    public static extern Result btdrvReadGattDescriptor(u32 connection_handle, bool is_primary, ref BtdrvGattId serv_id, ref BtdrvGattId char_id, ref BtdrvGattId desc_id, u8 auth_req);
    public static extern Result btdrvWriteGattCharacteristic(u32 connection_handle, bool is_primary, ref BtdrvGattId serv_id, ref BtdrvGattId char_id, IntPtr buffer, ulong size, u8 auth_req, bool with_response);
    public static extern Result btdrvWriteGattDescriptor(u32 connection_handle, bool is_primary, ref BtdrvGattId serv_id, ref BtdrvGattId char_id, ref BtdrvGattId desc_id, IntPtr buffer, ulong size, u8 auth_req);
    public static extern Result btdrvRegisterGattNotification(u32 connection_handle, bool is_primary, ref BtdrvGattId serv_id, ref BtdrvGattId char_id);
    public static extern Result btdrvUnregisterGattNotification(u32 connection_handle, bool is_primary, ref BtdrvGattId serv_id, ref BtdrvGattId char_id);
    public static extern Result btdrvGetLeHidEventInfo(IntPtr buffer, ulong size, ref BtdrvBleEventType type);
    public static extern Result btdrvRegisterBleHidEvent(ref Event out_event);
    public static extern Result btdrvSetBleScanParameter(u16 scan_interval, u16 scan_window);
    public static extern Result btdrvMoveToSecondaryPiconet(BtdrvAddress addr);
    public static extern Result btdrvIsBluetoothEnabled(ref bool @out);
    public static extern Result btdrvAcquireAudioEvent(ref Event out_event, bool autoclear);
    public static extern Result btdrvGetAudioEventInfo(IntPtr buffer, ulong size, ref BtdrvAudioEventType type);
    public static extern Result btdrvOpenAudioConnection(BtdrvAddress addr);
    public static extern Result btdrvCloseAudioConnection(BtdrvAddress addr);
    public static extern Result btdrvOpenAudioOut(BtdrvAddress addr, ref u32 audio_handle);
    public static extern Result btdrvCloseAudioOut(u32 audio_handle);
    public static extern Result btdrvStartAudioOut(u32 audio_handle, ref BtdrvPcmParameter pcm_param, s64 in_latency, ref s64 out_latency, ref u64 out1);
    public static extern Result btdrvStopAudioOut(u32 audio_handle);
    public static extern Result btdrvGetAudioOutState(u32 audio_handle, ref BtdrvAudioOutState @out);
    public static extern Result btdrvGetAudioOutFeedingCodec(u32 audio_handle, ref BtdrvAudioCodec @out);
    public static extern Result btdrvGetAudioOutFeedingParameter(u32 audio_handle, ref BtdrvPcmParameter @out);
    public static extern Result btdrvAcquireAudioOutStateChangedEvent(u32 audio_handle, ref Event out_event, bool autoclear);
    public static extern Result btdrvAcquireAudioOutBufferAvailableEvent(u32 audio_handle, ref Event out_event, bool autoclear);
    public static extern Result btdrvSendAudioData(u32 audio_handle, IntPtr buffer, ulong size, ref u64 transferred_size);
    public static extern Result btdrvAcquireAudioControlInputStateChangedEvent(ref Event out_event, bool autoclear);
    public static extern Result btdrvGetAudioControlInputState(ref BtdrvAudioControlButtonState states, s32 count, ref s32 total_out);
    public static extern Result btdrvAcquireAudioConnectionStateChangedEvent(ref Event out_event, bool autoclear);
    public static extern Result btdrvGetConnectedAudioDevice(ref BtdrvAddress addrs, s32 count, ref s32 total_out);
    public static extern Result btdrvCloseAudioControlInput(BtdrvAddress addr);
    public static extern Result btdrvRegisterAudioControlNotification(BtdrvAddress addr, u32 event_type);
    public static extern Result btdrvSendAudioControlPassthroughCommand(BtdrvAddress addr, u32 op_id, u32 state_type);
    public static extern Result btdrvSendAudioControlSetAbsoluteVolumeCommand(BtdrvAddress addr, s32 val);
    public static extern Result btdrvIsManufacturingMode(ref bool @out);
    public static extern Result btdrvEmulateBluetoothCrash(BtdrvFatalReason reason);
    public static extern Result btdrvGetBleChannelMap(ref BtdrvChannelMapList @out);
    public static extern IntPtr btdrvCircularBufferRead(ref BtdrvCircularBuffer c);
    public static extern bool btdrvCircularBufferFree(ref BtdrvCircularBuffer c);
}
